### ISSUE TITLE
Import error: ImportError: cannot import name 'iteritems' from 'click._compat

### ISSUE THREAD

**Issue by manishbhatt** [Nekmo/gkeep#45]
Python 3.8

**Comment by joelgsponer** [comment]
Hi, I do second this.
Running on a MacOS 10.15.7  with python 3.8. Tried reinstalling the clicker library but with no success.
Thanks for your work it looks like exactly what I was looking for.

**Comment by 0xConnorRhodes** [comment]
I am also experiencing this issue. I'm on Mac OS 11.5.2 with Python 3.9.7.

**Comment by averyfreeman** [comment]
```
PS C:\Windows\System32> gkeep help
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\gkeep.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\google_keep_tasks\management.py", line 5, in <module>
    from google_keep_tasks.auth import GoogleKeep
  File "C:\Python310\lib\site-packages\google_keep_tasks\auth.py", line 9, in <module>
    from google_keep_tasks.cli import choices_prompt
  File "C:\Python310\lib\site-packages\google_keep_tasks\cli.py", line 2, in <module>
    from click._compat import iteritems
ImportError: cannot import name 'iteritems' from 'click._compat' (C:\Python310\lib\site-packages\click\_compat.py)
```

Me as well, installed via `pip`, Windows 11 22000 x64, python 3.10.  Installed as administrator, running as administrator or non-elevated user same result.  Might see if I can install these libraries later, just wanted to send the code snippet before I got side-tracked.

Is this just a case of missing dependencies?

**Comment by Nekmo** [comment]
It may be a problem with dependencies. I will look at it. Thanks!

**Comment by Nekmo** [comment]
Added to v1.0.1 release, thanks!
