### ISSUE TITLE
How to install gkeep ( gkeep --auth ~/.gkeepauth FAILS)

### ISSUE THREAD

**Issue by bhishanpdl** [Nekmo/gkeep#9]
I like the idea of using google keep from the terminal.
I installed the gkeep using miniconda.
```
pip install gkeep
which gkeep # gkeep is /Users/poudel/miniconda3/bin/gkeep
```

Now, I created authentication file `~/.gkeepauth` and used the command
```
gkeep --auth ~/.gkeepauth   # failed
gkeep --auth "/Users/poudel/.gkeepauth"  # failed

$ gkeep --auth auth.txt
Usage: gkeep [OPTIONS] COMMAND [ARGS]...

Error: Missing command.
```

I also created auth.txt at source directory
```
echo "myusername mypasswd" > /Users/poudel/miniconda3/bin/auth.txt
```

Trying to use gkeep gives following error.
```
Bhishan at BpMacpro in ~/Temp
$ gkeep add-item 75e4202b0c1.9fc0b868a7b34952 "Chip cookies" --check
Traceback (most recent call last):
  File "/Users/poudel/miniconda2/bin/gkeep", line 7, in <module>
    catch(cli)()
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/google_keep_tasks/exceptions.py", line 31, in wrap
    fn(*args, **kwargs)
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/poudel/miniconda2/lib/python2.7/site-packages/google_keep_tasks/management.py", line 17, in cli
    except gkeepapi.LoginException:
AttributeError: 'module' object has no attribute 'LoginException'
```

How can we install `gkeep` ?

**Comment by Nekmo** [comment]
It seems that gkeepapi has changed its API. I'm going to create a patch release.

**Comment by Nekmo** [comment]
Download the latest version:

```
pip install -U gkeep
```

Thank you!
